service: ${env:SERVICE_NAME}

provider:
  name: aws
  runtime: ruby2.5
  stage: ${env:STAGE_ENV}
  region: ap-northeast-1
  role: ${env:LAMBDA_ROLE}
  deploymentBucket:
    name: ${env:DEPLOY_BUCKET}
  environment:
    RAILS_ENV: ${env:RAILS_ENV}
    RAILS_LOG_TO_STDOUT: ${env:RAILS_LOG_TO_STDOUT}
    RAILS_MASTER_KEY: ${env:RAILS_MASTER_KEY}

functions:
  hello:
    handler: handler.hello
