service: ${env:SERVICE_NAME}

provider:
  name: aws
  runtime: ruby2.5
  stage: ${env:STAGE_ENV}
  region: ${env:REGION}
  role: ${env:LAMBDA_ROLE}
  deploymentBucket:
    name: ${env:DEPLOY_BUCKET}
  environment:
    DYNAMO_PREFIX : ${env:DYNAMO_PREFIX}
    RAILS_ENV: ${env:RAILS_ENV}
    RAILS_MASTER_KEY: ${env:RAILS_MASTER_KEY}

functions:
  app:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
